replicaCount: 1
image:
  repository: ghcr.io/berriai/litellm
  tag: v1.74.7-stable.patch.2

service:
  enabled: true 
  type: LoadBalancer
  port: 4000

env:
  MODEL_LIST: '[{"model_name": "llama3", "litellm_provider": "ollama", "base_url": "http://ollama:11434"}]'
  PHOENIX_PORT: "6006"
  PHOENIX_API_KEY: "abc123"  # Use ArgoCD Secrets in production

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi