replicaCount: 1
image:
  repository: ghcr.io/berriai/litellm
  tag: v1.74.7-stable.patch.2

service:
  enabled: true
  type: LoadBalancer
  port: 4000

env:

  # Required configurations
  LITELLM_PROXY_API_API: "sk-1234"
  LITELLM_PROXY_API_BASE: "http://localhost:4000"  # Must match model_name above
  PUBLIC_MODEL_HUB: "True"

resources:
  requests:
    cpu: 250m
    memory: 500Mi
  limits:
    cpu: 1
    memory: 2Gi