# Default values for litellm-proxy
# This is a YAML-formatted file.

replicaCount: 1

image:
  repository: ghcr.io/berriai/litellm
  tag: "v1.74.7-stable.patch.2"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 4000
  targetPort: 4000
  protocol: TCP

container:
  port: 4000
  host: "0.0.0.0"

phoenix:
  enabled: true
  endpoint: "http://phoenix.litellm-poc.svc.cluster.local:6006" 

# LiteLLM Configuration
litellm:
  masterKey: "sk-1234"
  config:
    model_list:
      - model_name: "gpt-3.5-turbo"
        litellm_params:
          model: "huggingface/microsoft/DialoGPT-medium"
          api_base: "https://api-inference.huggingface.co/models/microsoft/DialoGPT-medium"
      - model_name: "llama2"
        litellm_params:
          model: "huggingface/meta-llama/Llama-2-7b-chat-hf"
          api_base: "https://api-inference.huggingface.co/models/meta-llama/Llama-2-7b-chat-hf"
      - model_name: "codellama"
        litellm_params:
          model: "huggingface/codellama/CodeLlama-7b-Instruct-hf"
          api_base: "https://api-inference.huggingface.co/models/codellama/CodeLlama-7b-Instruct-hf"
      - model_name: "mistral"
        litellm_params:
          model: "huggingface/mistralai/Mistral-7B-Instruct-v0.1"
          api_base: "https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.1"
    general_settings:
      master_key: "sk-1234"

# Health check configuration
healthCheck:
  liveness:
    path: /health
    initialDelaySeconds: 30
    periodSeconds: 30
  readiness:
    path: /health
    initialDelaySeconds: 10
    periodSeconds: 15

# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Node selector, tolerations and affinity
nodeSelector: {}
tolerations: []
affinity: {}

# Pod Security Context
podSecurityContext: {}

# Security Context
securityContext: {}

# Pod annotations
podAnnotations: {}

# Service account
serviceAccount:
  create: false
  annotations: {}
  name: ""