apiVersion: v1
kind: Service
metadata:
  name: litellm
spec:
  selector:
    app: litellm
  ports:
    - port: 4000
      targetPort: 4000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      containers:
        - name: litellm
          image: ghcr.io/berriai/litellm:v1.74.7-stable.patch.2
          ports:
            - containerPort: 4000
          env:
            - name: MODEL_LIST
              value: '[{"model_name": "llama3", "litellm_provider": "ollama", "base_url": "http://ollama:11434"}]'
            - name: PHOENIX_PORT
              value: "6006"
            - name: PHOENIX_API_KEY
              value: "abc123"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
