replicaCount: 1

image:
  repository: arizephoenix/phoenix
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 6006

env:
  PHOENIX_PORT: "6006"
  PHOENIX_API_KEY: ""  

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi