apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            # Core Proxy Configuration
            - name: LITELLM_MASTER_KEY
              value: {{ .Values.litellmConfig.masterKey | quote }}
            - name: LITELLM_ENVIRONMENT
              value: {{ .Values.litellmConfig.environment | quote }}
            
            # Model Configuration
            - name: LITELLM_COMPLETION_MODEL
              value: {{ .Values.litellmConfig.completionModel | quote }}
            - name: LITELLM_ALLOWED_MODELS
              value: {{ join "," .Values.litellmConfig.allowedModels | quote }}
            
            # Network Binding
            - name: LITELLM_HOST
              value: "0.0.0.0"
            - name: LITELLM_PORT
              value: {{ .Values.service.port | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}