---
apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: litellm-poc
data:
  config.yaml: |
    model_list:
      - model_name: "gpt-3.5-turbo"
        litellm_params:
          model: "gpt-3.5-turbo"
          api_key: "fake-key"
          
      - model_name: "gpt-4"
        litellm_params:
          model: "gpt-4"
          api_key: "fake-key"
          
      - model_name: "llama2"
        litellm_params:
          model: "replicate/llama-2-70b-chat"
          api_key: "fake-key"
          
      - model_name: "claude-3"
        litellm_params:
          model: "claude-3-sonnet-20240229"
          api_key: "fake-key"

    general_settings:
      master_key: "sk-1234"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm-proxy
  namespace: litellm-poc
  labels:
    app: litellm-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: litellm-proxy
  template:
    metadata:
      labels:
        app: litellm-proxy
    spec:
      containers:
      - name: litellm-proxy
        image: ghcr.io/berriai/litellm:v1.74.7-stable.patch.2
        command: ["litellm"]
        args: 
          - "--config"
          - "/app/config.yaml"
          - "--port"
          - "4000"
          - "--host"
          - "0.0.0.0"
        ports:
        - containerPort: 4000
          name: http
        env:
        - name: LITELLM_MASTER_KEY
          value: "sk-1234"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
            httpHeaders:
            - name: Authorization
              value: "Bearer sk-1234"
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health  
            port: 4000
            httpHeaders:
            - name: Authorization
              value: "Bearer sk-1234"
          initialDelaySeconds: 10
          periodSeconds: 15
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: config-volume
        configMap:
          name: litellm-config

---
apiVersion: v1
kind: Service
metadata:
  name: litellm-proxy
  namespace: litellm-poc
  labels:
    app: litellm-proxy
spec:
  type: LoadBalancer
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: http
  selector:
    app: litellm-proxy