apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: litellm-project
  source:
    repoURL: "https://github.com/Khani26-CloudDevops/LiteLLM-AKS-GITOPS.git"
    path: gitops/argocd/applications
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: "aks-litellm-muzeumix.hcp.eastus.azmk8s.io"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true